### ISSUE TITLE
live coredump breaks ptrace from 32-bit userspace to 64-bit PPC kernel

### ISSUE THREAD

**Issue by yuanjieh** [MontaVista-OpenSourceTechnology/linux-live-app-coredump#1]
With the live app coredump patch, COMPAT_SYS(ptrace) will be changed to PPC_SYS(ptrace), and the trampoline will redirect both calls from 32-bit and 64-bit userspace to sys_ptrace. This breaks all 32-bit userspace applications using ptrace, like a 32-bit gdb, debuggee will be killed by SIGILL.
```
(gdb) run
Starting program: /anytestcase
reading register r1 (#1): Input/output error.
Program received signal SIGILL, Illegal instruction.
0x00000000 in ?? ()
```
Therefore, I propose the attached patch, which creates dedicated trampolines.
[0001-powrepc-ptrace-Fix-syscall-from-32-bit-userland-to-6.patch.txt](https://github.com/cminyard/linux-live-app-coredump/files/570997/0001-powrepc-ptrace-Fix-syscall-from-32-bit-userland-to-6.patch.txt)

**Comment by cminyard** [comment]
What kernel version is this?
This has already sort of been fixed in current versions by using COMPAT_SYS() instead of PPC_SYS().  The only difference between that and your version is the call to .save_nvgprs, which I don't think is necessary.  Is there a reason you did this?

Also, I'm getting rid of the ptrace interface and moving to a procfs interface instead.

**Comment by yuanjieh** [comment]
Branches before v4.6-lacd are all affected.

**Comment by cminyard** [comment]
You didn't answer my question about COMPAT_SYS() and the call to .save_nvgprs.  Why do you need that call?

**Comment by cminyard** [comment]
Well, never mind, I see what is going on.

**Comment by cminyard** [comment]
Patch is applied.  Thanks.
